# -*- coding: utf-8 -*-
"""Doppi_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Nt0QatgAWpkJTAN0TdCiBUrLP4sbo3I
"""

!pip install ultralytics

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="o4Vv93v2E5r3NdcoZUGG")
project = rf.workspace("labelingdoppi").project("detecting-doppi")
dataset = project.version(3).download("yolov8")

!yolo task=detect mode=train model=yolov8s.pt data=/content/Detecting-Doppi-3/data.yaml epochs=50

!yolo mode=predict model=/content/runs/detect/train/weights/best.pt source=/content/doppi_rasm.jpg

!yolo mode=predict model=/content/runs/detect/train/weights/best.pt source=/content/doppi_video.mp4